package atraintegratedsystems.typeofapproval.repository;

import atraintegratedsystems.typeofapproval.model.TypeOfApprovalManufacturerDetail;
import org.springframework.data.jpa.repository.JpaRepository;

public interface TypeOfApprovalManufacturerDetail_Repository extends JpaRepository<TypeOfApprovalManufacturerDetail,Long> {
}
